# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Zey Enterprises
copyright: Zey Enterprises, LLC
logo: "/assets/images/ze-logo-344.png"
title_separator: "|"
email: arthur@zeyenterprises.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: air # this needs to be manually kept in sync with assets/css/main.scss @import "minimal-mistakes/skins/{{skin}}"
search: true

# Build settings
markdown: kramdown
# remote_theme: mmistakes/minimal-mistakes
theme: minimal-mistakes-jekyll
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Denver # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

repository: "Zey-Enterprises/web-main"
url: https://www.zeyenterprises.com

atom_feed:
  hide: true
lunr:
  search_within_pages: true


author:
  name   : "Arthur Zey"
  avatar : "/assets/images/arthur-zey.jpg"
  bio    : "logic-emotions monist; nerd; amateur bodybuilder"
  links:
    - label: "Personal Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.arthurzey.com"
      new_tab: true
    - label: "arthur@zeyenterprises.com"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:arthur@zeyenterprises.com"
    - label: "Messenger"
      icon: "fab fa-fw fa-facebook-messenger"
      url: "https://m.me/ArthurZey"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/ArthurZey"
      new_tab: true
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/arthurzey"
      new_tab: true
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/LogicalArthur"
      new_tab: true
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ArthurZey/"
      new_tab: true

# footer_scripts:
#  - /assets/js/no-avatar-dim.js

footer:
  links:
    # - label: "Twitter"
    #  icon: "fab fa-fw fa-twitter-square"
    #  url: "https://twitter.com/"
    # - label: "GitHub"
    #  icon: "fab fa-fw fa-github"
    #  url: "https://github.com/"
    # - label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: "https://instagram.com/"
    - label: "Messenger"
      icon: "fab fa-fw fa-facebook-messenger"
      url: "https://m.me/ArthurZey"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single-wide
      author_profile: true
      permalink: /:basename/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
